#!/usr/bin/env python3
import argparse
import os
import shutil
import tempfile
import urllib.request
import xml.etree.ElementTree as ET

import mujoco
import numpy as np

MENAGERIE_REF = "71f066ad0be9cd271f7ed58c030243ef157af9f4"
RAW_URL = "https://raw.githubusercontent.com/google-deepmind/mujoco_menagerie/{ref}/robotiq_2f85/{path}"
XML_NAME = "robotiq_2f85_menagerie.xml"
MESH_DIR = "meshes/robotiq_2f85"

MOUNT_QUAT = "0.70710678 0 0 0.70710678"
EEF_QUAT = "0 0 0 1"
GEOM_GROUP = {"2": "1", "3": "0"}

FT_SITE = dict(name="ft_frame", pos="0 0 0", size="0.01 0.01 0.01", rgba="1 0 0 1", type="sphere", group="1")
EEF_SITES = [
    dict(name="grip_site", pos="0 0 0", size="0.01 0.01 0.01", rgba="1 0 0 0.5", type="sphere", group="1"),
    dict(name="ee_x", pos="0.1 0 0", size="0.005 .1", quat="0.707105 0 0.707108 0", rgba="1 0 0 0",
         type="cylinder", group="1"),
    dict(name="ee_y", pos="0 0.1 0", size="0.005 .1", quat="0.707105 0.707108 0 0", rgba="0 1 0 0",
         type="cylinder", group="1"),
    dict(name="ee_z", pos="0 0 0.1", size="0.005 .1", quat="1 0 0 0", rgba="0 0 1 0", type="cylinder", group="1"),
    dict(name="grip_site_cylinder", pos="0 0 0", size="0.005 10", rgba="0 1 0 0.3", type="cylinder", group="1"),
]

FIELDS = """body_parentid body_pos body_quat body_ipos body_iquat body_mass body_inertia
    jnt_type jnt_bodyid jnt_pos jnt_axis jnt_range jnt_limited jnt_stiffness jnt_solref jnt_solimp qpos_spring
    dof_armature dof_damping dof_frictionloss
    geom_type geom_bodyid geom_dataid geom_matid geom_size geom_pos geom_quat geom_rgba geom_friction
    geom_solref geom_solimp geom_contype geom_conaffinity geom_condim geom_priority geom_group
    mesh_vertnum mesh_vert mat_rgba
    actuator_trntype actuator_trnid actuator_biastype actuator_gainprm actuator_biasprm actuator_gear
    actuator_ctrlrange actuator_forcerange actuator_forcelimited
    eq_type eq_obj1id eq_obj2id eq_data eq_solref eq_solimp
    tendon_num tendon_range tendon_limited tendon_stiffness tendon_damping tendon_lengthspring wrap_objid wrap_prm
    exclude_signature""".split()


def fetch(ref, path, dst):
    with urllib.request.urlopen(RAW_URL.format(ref=ref, path=path), timeout=60) as r:
        data = r.read()
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "wb") as f:
        f.write(data)


def default_classes(default, parent, out):
    table = {tag: dict(attrs) for tag, attrs in parent.items()}
    for el in default:
        if el.tag != "default":
            table[el.tag] = {**table.get(el.tag, {}), **el.attrib}
    out[default.get("class", "main")] = table
    for el in default.findall("default"):
        default_classes(el, table, out)
    return out


def flatten(root):
    default = root.find("default")
    classes = default_classes(default, {}, {}) if default is not None else {"main": {}}
    if default is not None:
        root.remove(default)

    def apply(el, cls, tag):
        for k, v in classes[el.attrib.pop("class", cls)].get(tag, {}).items():
            el.attrib.setdefault(k, v)

    def walk(body, cls):
        for el in body:
            if el.tag in ("body", "frame"):
                walk(el, el.attrib.pop("childclass", cls))
            elif el.tag in ("joint", "geom", "site", "camera", "light"):
                apply(el, cls, el.tag)

    for wb in root.findall("worldbody"):
        walk(wb, "main")
    for section, tag in [("asset", None), ("actuator", None), ("contact", None),
                         ("equality", "equality"), ("tendon", "tendon")]:
        for el in root.iterfind(section + "/*"):
            apply(el, "main", tag or el.tag)


def compare(ref, model):
    bad = []
    for f in FIELDS:
        a = np.asarray(getattr(ref, f), float)
        b = np.asarray(getattr(model, f), float)[:len(a)]
        if a.shape != b.shape or not np.allclose(a, b, rtol=0, atol=1e-9):
            bad.append(f)
    return bad


def num(v):
    return " ".join(f"{x:.9g}" for x in np.round(np.asarray(v, float), 12) + 0.0)


def wrap(flat, ref, ref_sha):
    root = ET.Element("mujoco", model="robotiq_2f85_menagerie")
    root.append(ET.Comment(
        f" Generated by sim/assets/build_gripper.py from mujoco_menagerie {ref_sha} robotiq_2f85/2f85.xml"
        " (BSD-2-Clause, see LICENSE). Do not edit; re-run the script. "))
    ET.SubElement(root, "compiler", {k: v for k, v in flat.find("compiler").attrib.items()
                                     if k not in ("meshdir", "texturedir", "assetdir")})
    for section in ("asset", "worldbody", "contact", "tendon", "equality", "actuator", "sensor"):
        el = flat.find(section)
        root.append(el if el is not None else ET.Element(section))

    for mesh in root.iterfind("asset/mesh"):
        stem = os.path.splitext(os.path.basename(mesh.get("file")))[0]
        mesh.attrib = {"name": mesh.get("name", stem), **mesh.attrib,
                       "file": f"{MESH_DIR}/{os.path.basename(mesh.get('file'))}"}
    for geom in root.iter("geom"):
        if geom.get("group") in GEOM_GROUP:
            geom.set("group", GEOM_GROUP[geom.get("group")])
    for body in root.find("worldbody").iter("body"):
        if body.find("inertial") is None:
            b = ref.body(body.get("name"))
            body.insert(0, ET.Element("inertial", pos=num(b.ipos), quat=num(b.iquat), mass=num(b.mass),
                                      diaginertia=num(b.inertia)))

    base = root.find("worldbody/body")
    base.set("quat", MOUNT_QUAT)
    base.insert(0, ET.Element("site", FT_SITE))
    data = mujoco.MjData(ref)
    mujoco.mj_kinematics(ref, data)
    pinch = data.xmat[1].reshape(3, 3).T @ (data.site("pinch").xpos - data.xpos[1])
    eef = ET.SubElement(base, "body", name="eef", pos=num(pinch), quat=EEF_QUAT)
    for site in EEF_SITES:
        ET.SubElement(eef, "site", site)
    sensor = root.find("sensor")
    ET.SubElement(sensor, "force", name="force_ee", site="ft_frame")
    ET.SubElement(sensor, "torque", name="torque_ee", site="ft_frame")
    return root


def write_xml(root, path):
    tree = ET.ElementTree(root)
    ET.indent(tree, "  ")
    tree.write(path, encoding="unicode")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    p = argparse.ArgumentParser(
        description=(
            "Build the MuJoCo Menagerie Robotiq 2F-85 gripper for robosuite 1.4 from robotiq_2f85/2f85.xml\n"
            "at a pinned mujoco_menagerie commit:\n\n"
            "  <out>/grippers/robotiq_2f85_menagerie.xml   robosuite GripperModel XML\n"
            "  <out>/grippers/meshes/robotiq_2f85/*.stl    its meshes (file= is relative to the XML)\n"
            "  <out>/grippers/LICENSE                      robotiq_2f85's license (BSD-2-Clause)\n\n"
            "The default <out> is this directory, where kinova_env looks. With --out DIR,\n"
            "export KINOVA_SIM_ASSETS=DIR."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--out", default=here, help="writes <out>/grippers/ (default: %(default)s)")
    p.add_argument("--ref", default=MENAGERIE_REF, help="mujoco_menagerie commit (default: %(default)s)")
    args = p.parse_args()
    out = os.path.join(os.path.abspath(os.path.expanduser(args.out)), "grippers")

    with tempfile.TemporaryDirectory() as tmp:
        up = os.path.join(tmp, "2f85.xml")
        fetch(args.ref, "2f85.xml", up)
        tree = ET.parse(up)
        meshdir = tree.find("compiler").get("meshdir", "")
        meshes = sorted({m.get("file") for m in tree.iterfind("asset/mesh")})
        for f in meshes:
            fetch(args.ref, f"{meshdir}/{f}", os.path.join(tmp, meshdir, f))
        fetch(args.ref, "LICENSE", os.path.join(tmp, "LICENSE"))
        print(f"[fetch] mujoco_menagerie@{args.ref} robotiq_2f85: 2f85.xml, LICENSE, {len(meshes)} meshes")

        ref = mujoco.MjModel.from_xml_path(up)
        flat = tree.getroot()
        flatten(flat)
        write_xml(flat, os.path.join(tmp, "flat.xml"))
        bad = compare(ref, mujoco.MjModel.from_xml_path(os.path.join(tmp, "flat.xml")))
        if bad:
            raise SystemExit(f"[check] FAIL: flattened model differs from upstream in {bad}")
        print(f"[check] flattened == upstream: {len(FIELDS)} compiled arrays match "
              f"({ref.nbody} bodies, {ref.njnt} joints, {ref.ngeom} geoms, {ref.nu} actuator)")

        gdir = os.path.join(tmp, "grippers")
        os.makedirs(os.path.join(gdir, MESH_DIR))
        for f in meshes:
            shutil.copy(os.path.join(tmp, meshdir, f), os.path.join(gdir, MESH_DIR, f))
        shutil.copy(os.path.join(tmp, "LICENSE"), gdir)
        wrapped = wrap(flat, ref, args.ref)
        write_xml(wrapped, os.path.join(gdir, XML_NAME))
        wrapped.find("compiler").set("inertiagrouprange", "0 0")
        write_xml(wrapped, os.path.join(gdir, "check.xml"))
        m = mujoco.MjModel.from_xml_path(os.path.join(gdir, "check.xml"))
        os.remove(os.path.join(gdir, "check.xml"))
        mount = np.array([float(x) for x in MOUNT_QUAT.split()])
        if not np.allclose(m.body_quat[1], mount / np.linalg.norm(mount)):
            raise SystemExit("[check] FAIL: mount rotation not on the root body")
        if not all(str(g) == GEOM_GROUP.get(str(r), str(r)) for g, r in zip(m.geom_group, ref.geom_group)):
            raise SystemExit("[check] FAIL: geom groups not remapped")
        m.body_quat[1] = ref.body_quat[1]
        m.geom_group[:] = ref.geom_group
        bad = compare(ref, m)
        d = mujoco.MjData(m)
        mujoco.mj_kinematics(m, d)
        if bad or not np.allclose(d.site("grip_site").xpos, d.site("pinch").xpos, atol=1e-6):
            raise SystemExit(f"[check] FAIL: wrapped model differs from upstream in {bad or 'grip_site'}")
        hinges = sum(m.jnt_type == mujoco.mjtJoint.mjJNT_HINGE)
        print(f"[check] wrapped (inertiagrouprange 0 0) == upstream except mount/groups; "
              f"{hinges} hinge joints, actuator ctrlrange {m.actuator_ctrlrange[0]}, grip_site on pinch")

        shutil.rmtree(os.path.join(out, MESH_DIR), ignore_errors=True)
        shutil.copytree(gdir, out, dirs_exist_ok=True)
    for f in [XML_NAME, "LICENSE"] + [f"{MESH_DIR}/{f}" for f in meshes]:
        print(f"[write] {os.path.join(out, f)}")


if __name__ == "__main__":
    main()
